apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::397931825173:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19HGB3F5XMD6Z
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::397931825173:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-22T03:25:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1372"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9286ed64-9a00-4a32-953a-4ef6d10067af
